### ISSUE TITLE
Add support for dot

### ISSUE THREAD

**Issue by wucke13** [Kixunil/seven_segment#1]
Most seven segment displays come with an eighth segment, the dot. Please add support for that to this crate.

**Comment by Kixunil** [comment]
I considered this, but I concluded it's not actually needed, as the API would be the same as manually setting the pin outside of this crate. But maybe I'm missing something and there's something that'd make it simpler? In that case, I'm willing to reevaluate the idea.

**Comment by wucke13** [comment]
That is a good point. I think this only makes sense if the API is extended by a way of controlling multiple SSDs. However I'm not convinced that that would be a good Idea.

**Comment by Kixunil** [comment]
Yeah, closing for now. One idea was to add a higher-level API capable of displaying decimal numbers, but I'd implement it in another crate as that is a concern of another layer.
