### ISSUE TITLE
Add support for hex numbers

### ISSUE THREAD

**Issue by wucke13** [Kixunil/seven_segment#2]
I think it is a valid usecase to display both decimal and hexadecimal numbers on a seven segment display. Please add them. Find my proposal for the displaying of the characters attached (taken from an old C project of mine):

```
case 0x0A:return 1|32|2|64|16|4;
case 0x0B:return 4|8|16|32|64;
case 0x0C:return 1|32|16|8;
case 0x0D:return 2|16|4|8|64;
case 0x0E:return 1|32|64|16|8;
case 0x0F:return 1|32|64|16;
```

One should re ensemble A, two should be B, 4 should be C and so on.

**Comment by Kixunil** [comment]
Good idea! I don't have much time now, but willing to merge the PR. Adding those cases into match should be sufficient I think.
